/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#b5b5b8",
        "on-tertiary": "#2f3133",
        "secondary-fixed-dim": "#cebdff",
        "surface-container": "#1f201e",
        "on-primary-fixed": "#0a2011",
        background: "#121412",
        "lavender-mist": "#c8b6ff",
        "on-secondary-fixed-variant": "#4c3c7c",
        "on-tertiary-fixed-variant": "#454749",
        "on-tertiary-fixed": "#1a1c1e",
        "on-primary-fixed-variant": "#364c3b",
        "midnight-slate": "#0f1113",
        "on-secondary-fixed": "#200d4e",
        "surface-dim": "#121412",
        "on-background": "#e3e2df",
        surface: "#121412",
        "on-secondary": "#352564",
        "on-surface": "#e3e2df",
        "surface-container-lowest": "#0d0e0d",
        "deep-slate": "#1a1c1e",
        "primary-fixed": "#cfe9d2",
        "inverse-on-surface": "#30312f",
        "tertiary-fixed-dim": "#c6c6c9",
        "on-tertiary-container": "#454749",
        primary: "#bed8c1",
        "surface-tint": "#b4cdb6",
        "inverse-primary": "#4d6451",
        tertiary: "#d0d1d3",
        "tertiary-fixed": "#e2e2e5",
        error: "#ffb4ab",
        "secondary-fixed": "#e8ddff",
        "on-secondary-container": "#bcabf3",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#1b1c1a",
        "surface-container-highest": "#343533",
        outline: "#8d928b",
        "primary-fixed-dim": "#b4cdb6",
        "error-container": "#93000a",
        "surface-bright": "#383938",
        "on-error": "#690005",
        "secondary-container": "#4c3c7c",
        "on-primary": "#203525",
        "on-surface-variant": "#c3c8c0",
        "outline-variant": "#434843",
        "surface-variant": "#343533",
        "surface-container-high": "#292a28",
        "inverse-surface": "#e3e2df",
        "on-primary-container": "#364c3b",
        "primary-container": "#a3bca6",
        "sage-glow": "#a3bca6",
        secondary: "#cebdff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "24px",
        "section-gap": "48px",
        "margin-desktop": "64px",
        unit: "8px",
        gutter: "16px",
        "container-padding-desktop": "64px",
        "container-padding-mobile": "24px",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
